name: hy_thon_team3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.7+4
  permission_handler: ^10.2.0
  http: ^1.2.2
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.6
  flutter_lints: ^3.0.0
  shared_preferences: ^2.1.1
  table_calendar: ^3.0.9


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#07BEB8"
  image: assets/images/icon_book.png
